// <auto-generated />
namespace Price_comparison_engine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SukurtiKomentaruStulpeli1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SukurtiKomentaruStulpeli1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010080936285_SukurtiKomentaruStulpeli1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
